version: "2"
services:
  app:
    container_name: 'bnkp-hilihao-app'
    build: .
    ports: 
      - "80:3000"
    volumes:
      - "./:/usr/src/app"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: bnkp-hilihao
      POSTGRES_PASSWORD: password
    