version: "2"
services:
  app:
    container_name: 'bnkp-hilihao-app'
    build: .
    ports: 
      - "80:80"
    volumes:
      - "./:/usr/src/app"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: bnkp-hilihao
      POSTGRES_PASSWORD: password
      DOMAIN_1: bnkp-hilihao.test|/usr/src/app|rails
    